// <auto-generated />
using System;
using GloryLikeBackend.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GloryLikeBackend.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("GloryLikeBackend.Models.Ai.SkillQuestionnaire", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("GeneratedByModel")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<int>("QuestionCount")
                        .HasColumnType("int");

                    b.Property<string>("Seniority")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("SkillComplexity")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int?>("SkillId")
                        .HasColumnType("int");

                    b.Property<string>("SkillName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("StructureJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("Version")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SkillName", "Seniority", "SkillComplexity", "Language", "Version", "Status")
                        .HasDatabaseName("IX_SkillQuestionnaires_CacheLookup");

                    b.ToTable("SkillQuestionnaires", (string)null);
                });

            modelBuilder.Entity("GloryLikeBackend.Models.JobOffer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1500)
                        .HasColumnType("nvarchar(1500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("RequiredJob")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Seniority")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Skills")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SkillsWeight")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("JobOffers");
                });

            modelBuilder.Entity("GloryLikeBackend.Models.SkillAndJob.JobFamily", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("JobName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("Id");

                    b.HasIndex("JobName")
                        .IsUnique()
                        .HasDatabaseName("UX_JobFamilies_JobName");

                    b.ToTable("JobFamilies");
                });

            modelBuilder.Entity("GloryLikeBackend.Models.SkillAndJob.Position", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("JobFamilyId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("Id");

                    b.HasIndex("JobFamilyId")
                        .HasDatabaseName("IX_Positions_JobFamilyId");

                    b.HasIndex("JobFamilyId", "Name")
                        .IsUnique()
                        .HasDatabaseName("UX_Positions_JobFamilyId_Name");

                    b.ToTable("Positions");
                });

            modelBuilder.Entity("GloryLikeBackend.Models.SkillAndJob.PositionSeniority", b =>
                {
                    b.Property<int>("PositionId")
                        .HasColumnType("int");

                    b.Property<int>("SeniorityId")
                        .HasColumnType("int");

                    b.HasKey("PositionId", "SeniorityId");

                    b.HasIndex("SeniorityId")
                        .HasDatabaseName("IX_PositionSeniorities_SeniorityId");

                    b.ToTable("PositionSeniorities");
                });

            modelBuilder.Entity("GloryLikeBackend.Models.SkillAndJob.Seniority", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("UX_Seniorities_Name");

                    b.HasIndex("SortOrder")
                        .IsUnique()
                        .HasDatabaseName("UX_Seniorities_SortOrder");

                    b.ToTable("Seniorities");
                });

            modelBuilder.Entity("GloryLikeBackend.Models.SkillAndJob.Skill", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AssessmentType")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasDefaultValue("TP");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<bool>("IsCore")
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<int>("MinimumSenioritySortOrder")
                        .HasColumnType("int")
                        .HasDefaultValue(1);

                    b.Property<int>("PositionId")
                        .HasColumnType("int");

                    b.Property<string>("SkillName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("VerificationMethod")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)")
                        .HasDefaultValue("");

                    b.HasKey("Id");

                    b.HasIndex("PositionId")
                        .HasDatabaseName("IX_Skills_PositionId");

                    b.HasIndex("PositionId", "SkillName")
                        .IsUnique()
                        .HasDatabaseName("UX_Skills_PositionId_SkillName");

                    b.ToTable("Skills");
                });

            modelBuilder.Entity("GloryLikeBackend.Models.CompanyCandidateMessage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<int>("CandidateUserId")
                        .HasColumnType("int");

                    b.Property<int>("CompanyOwnerUserId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ReadAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<int>("RecipientUserId")
                        .HasColumnType("int");

                    b.Property<int>("SenderUserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CandidateUserId");

                    b.HasIndex("CompanyOwnerUserId");

                    b.HasIndex("RecipientUserId");

                    b.HasIndex("SenderUserId");

                    b.HasIndex("CompanyOwnerUserId", "CandidateUserId", "CreatedAtUtc")
                        .HasDatabaseName("IX_CompanyCandidateMessages_CandidateThread");

                    b.HasIndex("CompanyOwnerUserId", "RecipientUserId", "ReadAtUtc")
                        .HasDatabaseName("IX_CompanyCandidateMessages_RecipientUnread");

                    b.ToTable("CompanyCandidateMessages", (string)null, t =>
                        {
                            t.HasCheckConstraint(
                                "CK_CompanyCandidateMessages_DifferentUsers",
                                "[SenderUserId] <> [RecipientUserId]");
                        });
                });

            modelBuilder.Entity("GloryLikeBackend.Models.CompanyTeamInvitation", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("AcceptedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<int?>("AcceptedUserId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<DateTime>("ExpiresAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<int>("OwnerUserId")
                        .HasColumnType("int");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<DateTime>("SentAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("AcceptedUserId")
                        .HasDatabaseName("IX_CompanyTeamInvitations_AcceptedUserId");

                    b.HasIndex("OwnerUserId", "Email")
                        .IsUnique()
                        .HasDatabaseName("UX_CompanyTeamInvitations_Owner_Email");

                    b.HasIndex("TokenHash")
                        .IsUnique()
                        .HasDatabaseName("UX_CompanyTeamInvitations_TokenHash");

                    b.ToTable("CompanyTeamInvitations", (string)null);
                });

            modelBuilder.Entity("GloryLikeBackend.Models.CompanyHiringPlan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CompanyOwnerUserId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<int>("CreatedByUserId")
                        .HasColumnType("int");

                    b.Property<string>("DepartmentName")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<string>("EmploymentType")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<int>("Headcount")
                        .HasColumnType("int");

                    b.Property<int?>("JobFamilyId")
                        .HasColumnType("int");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int?>("PositionId")
                        .HasColumnType("int");

                    b.Property<string>("PositionName")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("nvarchar(160)");

                    b.Property<string>("Priority")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("SeniorityId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("TargetStartDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CompanyOwnerUserId")
                        .HasDatabaseName("IX_CompanyHiringPlans_CompanyOwnerUserId");

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("JobFamilyId")
                        .HasDatabaseName("IX_CompanyHiringPlans_JobFamilyId");

                    b.HasIndex("PositionId")
                        .HasDatabaseName("IX_CompanyHiringPlans_PositionId");

                    b.HasIndex("SeniorityId")
                        .HasDatabaseName("IX_CompanyHiringPlans_SeniorityId");

                    b.ToTable("CompanyHiringPlans", (string)null);
                });

            modelBuilder.Entity("GloryLikeBackend.Models.CompanyProfile", b =>
                {
                    b.Property<string>("AboutPageCustomHtml")
                        .IsRequired()
                        .HasMaxLength(60000)
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AboutPageLayoutJson")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ActivityScope")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<string>("BenefitsJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CompanyAddress")
                        .IsRequired()
                        .HasMaxLength(240)
                        .HasColumnType("nvarchar(240)");

                    b.Property<string>("CompanyCity")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("CompanyCountry")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("CompanyCulture")
                        .IsRequired()
                        .HasMaxLength(1600)
                        .HasColumnType("nvarchar(1600)");

                    b.Property<string>("CompanyDescription")
                        .IsRequired()
                        .HasMaxLength(2500)
                        .HasColumnType("nvarchar(2500)");

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("nvarchar(160)");

                    b.Property<string>("CompanyType")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<string>("CompanyVideo")
                        .IsRequired()
                        .HasMaxLength(240)
                        .HasColumnType("nvarchar(240)");

                    b.Property<string>("CoverImageDataUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("EmployeeCount")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("FacebookUrl")
                        .IsRequired()
                        .HasMaxLength(240)
                        .HasColumnType("nvarchar(240)");

                    b.Property<int?>("FoundationYear")
                        .HasColumnType("int");

                    b.Property<string>("InstagramUrl")
                        .IsRequired()
                        .HasMaxLength(240)
                        .HasColumnType("nvarchar(240)");

                    b.Property<string>("LinkedInUrl")
                        .IsRequired()
                        .HasMaxLength(240)
                        .HasColumnType("nvarchar(240)");

                    b.Property<string>("LogoDataUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("OwnerUserId")
                        .HasColumnType("int");

                    b.Property<string>("PageLanguage")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<string>("TelegramUrl")
                        .IsRequired()
                        .HasMaxLength(240)
                        .HasColumnType("nvarchar(240)");

                    b.Property<string>("TiktokUrl")
                        .IsRequired()
                        .HasMaxLength(240)
                        .HasColumnType("nvarchar(240)");

                    b.Property<int>("UpdatedByUserId")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<bool>("UseCustomAboutPageHtml")
                        .HasColumnType("bit");

                    b.Property<string>("Website")
                        .IsRequired()
                        .HasMaxLength(240)
                        .HasColumnType("nvarchar(240)");

                    b.Property<string>("WhyWorkWithUs")
                        .IsRequired()
                        .HasMaxLength(1600)
                        .HasColumnType("nvarchar(1600)");

                    b.Property<string>("YoutubeUrl")
                        .IsRequired()
                        .HasMaxLength(240)
                        .HasColumnType("nvarchar(240)");

                    b.HasKey("Id");

                    b.HasIndex("OwnerUserId")
                        .IsUnique()
                        .HasDatabaseName("UX_CompanyProfiles_OwnerUserId");

                    b.HasIndex("UpdatedByUserId");

                    b.ToTable("CompanyProfiles", (string)null);
                });

            modelBuilder.Entity("GloryLikeBackend.Models.CompanyLocation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(240)
                        .HasColumnType("nvarchar(240)");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("CompanyProfileId")
                        .HasColumnType("int");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CompanyProfileId")
                        .HasDatabaseName("IX_CompanyLocations_CompanyProfileId");

                    b.ToTable("CompanyLocations", (string)null);
                });

            modelBuilder.Entity("GloryLikeBackend.Models.CompanyStructureDepartment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CompanyOwnerUserId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CompanyOwnerUserId", "SortOrder")
                        .HasDatabaseName("IX_CompanyStructureDepartments_Owner_SortOrder");

                    b.HasIndex("CompanyOwnerUserId", "Name")
                        .IsUnique()
                        .HasDatabaseName("UX_CompanyStructureDepartments_Owner_Name");

                    b.ToTable("CompanyStructureDepartments", (string)null);
                });

            modelBuilder.Entity("GloryLikeBackend.Models.CompanyStructureDivision", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DepartmentId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentId", "SortOrder")
                        .HasDatabaseName("IX_CompanyStructureDivisions_Department_SortOrder");

                    b.HasIndex("DepartmentId", "Name")
                        .IsUnique()
                        .HasDatabaseName("UX_CompanyStructureDivisions_Department_Name");

                    b.ToTable("CompanyStructureDivisions", (string)null);
                });

            modelBuilder.Entity("GloryLikeBackend.Models.CompanyStructurePosition", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DivisionId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("nvarchar(160)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DivisionId", "SortOrder")
                        .HasDatabaseName("IX_CompanyStructurePositions_Division_SortOrder");

                    b.HasIndex("DivisionId", "Name")
                        .IsUnique()
                        .HasDatabaseName("UX_CompanyStructurePositions_Division_Name");

                    b.ToTable("CompanyStructurePositions", (string)null);
                });

            modelBuilder.Entity("GloryLikeBackend.Models.PendingEmailRegistration", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AccountType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("CompanyName")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("CompanyType")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<int>("FailedAttemptCount")
                        .HasColumnType("int");

                    b.Property<string>("Industry")
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<DateTime>("LastSentAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("ProfileName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<DateTime>("ResendAvailableAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("TeamInvitationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("VerificationCodeHash")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("VerificationCodeExpiresAtUtc")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("UX_PendingEmailRegistrations_Email");

                    b.HasIndex("TeamInvitationId")
                        .HasDatabaseName("IX_PendingEmailRegistrations_TeamInvitationId");

                    b.HasIndex("VerificationCodeExpiresAtUtc")
                        .HasDatabaseName("IX_PendingEmailRegistrations_ExpiresAtUtc");

                    b.ToTable("PendingEmailRegistrations", (string)null);
                });

            modelBuilder.Entity("GloryLikeBackend.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AccountType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("candidate");

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<string>("About")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime?>("BirthDate")
                        .HasColumnType("date");

                    b.Property<string>("CompanyName")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("CompanyType")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<DateTime?>("EmailVerifiedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("FatherName")
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<string>("Industry")
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime?>("PasswordResetCodeExpiresAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("PasswordResetCodeHash")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("ProfileImageDataUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("UX_Users_Email");

                    b.HasIndex("PhoneNumber")
                        .IsUnique()
                        .HasFilter("[PhoneNumber] IS NOT NULL")
                        .HasDatabaseName("UX_Users_PhoneNumber");

                    b.HasIndex("UserName")
                        .IsUnique()
                        .HasDatabaseName("UX_Users_UserName");

                    b.ToTable("Users", (string)null);
                });

            modelBuilder.Entity("GloryLikeBackend.Models.Vacancies.Vacancy", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("AllowInternalCandidates")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ApplicationDeadline")
                        .HasColumnType("datetime2");

                    b.Property<bool>("AutoRejectBelowScore")
                        .HasColumnType("bit");

                    b.Property<string>("ClientRequisitionCode")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ContactEmail")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<int>("CompanyOwnerUserId")
                        .HasColumnType("int");

                    b.Property<int?>("CompanyLocationId")
                        .HasColumnType("int");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("EducationLevel")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("EducationRequirement")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("EmployerUserId")
                        .HasColumnType("int");

                    b.Property<string>("EmploymentType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ExperienceRequired")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("HideSalary")
                        .HasColumnType("bit");

                    b.Property<int?>("HiringPlanId")
                        .HasColumnType("int");

                    b.Property<int>("InterviewRounds")
                        .HasColumnType("int");

                    b.Property<string>("JobDescription")
                        .IsRequired()
                        .HasMaxLength(5000)
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("JobFamilyId")
                        .HasColumnType("int");

                    b.Property<string>("JobFamilyName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("LocationName")
                        .IsRequired()
                        .HasMaxLength(460)
                        .HasColumnType("nvarchar(460)");

                    b.Property<decimal?>("MaxSalary")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("MinSalary")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("MinimumMatchScore")
                        .HasColumnType("int");

                    b.Property<int>("MinimumTrustScore")
                        .HasColumnType("int");

                    b.Property<int>("MinimumVerificationLevel")
                        .HasColumnType("int");

                    b.Property<bool>("NotifyMatchingCandidates")
                        .HasColumnType("bit");

                    b.Property<string>("PaymentTerms")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("PlatformVacancyId")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<int>("PositionId")
                        .HasColumnType("int");

                    b.Property<string>("PositionName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("PublicationPriority")
                        .HasColumnType("int");

                    b.Property<DateTime?>("PublishDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("RequireVerifiedCoreSkills")
                        .HasColumnType("bit");

                    b.Property<string>("RoleTitle")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("ScreeningNotes")
                        .IsRequired()
                        .HasMaxLength(5000)
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ScreeningSlaDays")
                        .HasColumnType("int");

                    b.Property<int>("SeniorityId")
                        .HasColumnType("int");

                    b.Property<string>("SeniorityName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("SourcePayloadJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("StageApplied")
                        .HasColumnType("bit");

                    b.Property<bool>("StageInterview")
                        .HasColumnType("bit");

                    b.Property<bool>("StageOffer")
                        .HasColumnType("bit");

                    b.Property<bool>("StageScreening")
                        .HasColumnType("bit");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Visibility")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAtUtc")
                        .HasDatabaseName("IX_Vacancies_CreatedAtUtc");

                    b.HasIndex("CompanyOwnerUserId")
                        .HasDatabaseName("IX_Vacancies_CompanyOwnerUserId");

                    b.HasIndex("CompanyLocationId")
                        .HasDatabaseName("IX_Vacancies_CompanyLocationId");

                    b.HasIndex("EmployerUserId")
                        .HasDatabaseName("IX_Vacancies_EmployerUserId");

                    b.HasIndex("JobFamilyId");

                    b.HasIndex("HiringPlanId")
                        .HasDatabaseName("IX_Vacancies_HiringPlanId");

                    b.HasIndex("PlatformVacancyId")
                        .IsUnique()
                        .HasDatabaseName("UX_Vacancies_PlatformVacancyId");

                    b.HasIndex("PositionId")
                        .HasDatabaseName("IX_Vacancies_PositionId");

                    b.HasIndex("SeniorityId");

                    b.ToTable("Vacancies", (string)null);
                });

            modelBuilder.Entity("GloryLikeBackend.Models.Vacancies.VacancyApplication", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("AppliedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<int>("CandidateUserId")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<int>("VacancyId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CandidateUserId")
                        .HasDatabaseName("IX_VacancyApplications_CandidateUserId");

                    b.HasIndex("VacancyId", "CandidateUserId")
                        .IsUnique()
                        .HasDatabaseName("UX_VacancyApplications_VacancyId_CandidateUserId");

                    b.ToTable("VacancyApplications", (string)null);
                });

            modelBuilder.Entity("GloryLikeBackend.Models.Vacancies.VacancyApplicationRequirement", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("FieldKey")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsCustom")
                        .HasColumnType("bit");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("RequirementMode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.Property<int>("VacancyId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("VacancyId", "FieldKey")
                        .IsUnique()
                        .HasDatabaseName("UX_VacancyApplicationRequirements_VacancyId_FieldKey");

                    b.ToTable("VacancyApplicationRequirements", (string)null);
                });

            modelBuilder.Entity("GloryLikeBackend.Models.Vacancies.VacancyScreeningAnswer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AnswerDisplayText")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<string>("AnswerType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("AnswerValueJson")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<bool?>("IsCorrect")
                        .HasColumnType("bit");

                    b.Property<string>("QuestionText")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("RequirementType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("ScreeningQuestionId")
                        .HasColumnType("int");

                    b.Property<int>("VacancyApplicationId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("VacancyApplicationId", "ScreeningQuestionId")
                        .IsUnique()
                        .HasDatabaseName("UX_VacancyScreeningAnswers_ApplicationId_QuestionId");

                    b.ToTable("VacancyScreeningAnswers", (string)null);
                });

            modelBuilder.Entity("GloryLikeBackend.Models.Vacancies.VacancyBenefit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.Property<int>("VacancyId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("VacancyId", "Name")
                        .IsUnique()
                        .HasDatabaseName("UX_VacancyBenefits_VacancyId_Name");

                    b.ToTable("VacancyBenefits", (string)null);
                });

            modelBuilder.Entity("GloryLikeBackend.Models.Vacancies.VacancyFunnelStage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Hours")
                        .HasColumnType("int");

                    b.Property<bool>("IsStandard")
                        .HasColumnType("bit");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.Property<string>("StageName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("VacancyId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("VacancyId", "SortOrder")
                        .HasDatabaseName("IX_VacancyFunnelStages_VacancyId");

                    b.ToTable("VacancyFunnelStages", (string)null);
                });

            modelBuilder.Entity("GloryLikeBackend.Models.Vacancies.VacancyPublicationChannel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ChannelName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ChannelType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("bit");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.Property<int>("VacancyId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("VacancyId", "ChannelName")
                        .IsUnique()
                        .HasDatabaseName("UX_VacancyPublicationChannels_VacancyId_ChannelName");

                    b.ToTable("VacancyPublicationChannels", (string)null);
                });

            modelBuilder.Entity("GloryLikeBackend.Models.Vacancies.VacancyScreeningQuestion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AnswerType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("QuestionText")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("RequirementType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.Property<int>("VacancyId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("VacancyId", "SortOrder")
                        .HasDatabaseName("IX_VacancyScreeningQuestions_VacancyId");

                    b.ToTable("VacancyScreeningQuestions", (string)null);
                });

            modelBuilder.Entity("GloryLikeBackend.Models.Vacancies.VacancyScreeningChoice", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ChoiceText")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<bool>("IsCorrect")
                        .HasColumnType("bit");

                    b.Property<int>("ScreeningQuestionId")
                        .HasColumnType("int");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ScreeningQuestionId", "SortOrder")
                        .HasDatabaseName("IX_VacancyScreeningChoices_QuestionId");

                    b.ToTable("VacancyScreeningChoices", (string)null);
                });

            modelBuilder.Entity("GloryLikeBackend.Models.Vacancies.VacancySkillRequirement", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("MinimumVerificationLevel")
                        .HasColumnType("int");

                    b.Property<string>("RequirementType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("SkillId")
                        .HasColumnType("int");

                    b.Property<string>("SkillName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.Property<int>("VacancyId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SkillId");

                    b.HasIndex("VacancyId", "SkillId")
                        .IsUnique()
                        .HasDatabaseName("UX_VacancySkillRequirements_VacancyId_SkillId");

                    b.ToTable("VacancySkillRequirements", (string)null);
                });

            modelBuilder.Entity("GloryLikeBackend.Models.CompanyCandidateMessage", b =>
                {
                    b.HasOne("GloryLikeBackend.Models.User", "Candidate")
                        .WithMany()
                        .HasForeignKey("CandidateUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GloryLikeBackend.Models.User", "CompanyOwner")
                        .WithMany()
                        .HasForeignKey("CompanyOwnerUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GloryLikeBackend.Models.User", "Recipient")
                        .WithMany()
                        .HasForeignKey("RecipientUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GloryLikeBackend.Models.User", "Sender")
                        .WithMany()
                        .HasForeignKey("SenderUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Candidate");

                    b.Navigation("CompanyOwner");

                    b.Navigation("Recipient");

                    b.Navigation("Sender");
                });

            modelBuilder.Entity("GloryLikeBackend.Models.CompanyTeamInvitation", b =>
                {
                    b.HasOne("GloryLikeBackend.Models.User", "AcceptedUser")
                        .WithMany()
                        .HasForeignKey("AcceptedUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("GloryLikeBackend.Models.User", "OwnerUser")
                        .WithMany()
                        .HasForeignKey("OwnerUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AcceptedUser");

                    b.Navigation("OwnerUser");
                });

            modelBuilder.Entity("GloryLikeBackend.Models.CompanyLocation", b =>
                {
                    b.HasOne("GloryLikeBackend.Models.CompanyProfile", "CompanyProfile")
                        .WithMany("Locations")
                        .HasForeignKey("CompanyProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CompanyProfile");
                });

            modelBuilder.Entity("GloryLikeBackend.Models.CompanyStructureDepartment", b =>
                {
                    b.HasOne("GloryLikeBackend.Models.User", "CompanyOwnerUser")
                        .WithMany()
                        .HasForeignKey("CompanyOwnerUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CompanyOwnerUser");
                });

            modelBuilder.Entity("GloryLikeBackend.Models.CompanyStructureDivision", b =>
                {
                    b.HasOne("GloryLikeBackend.Models.CompanyStructureDepartment", "Department")
                        .WithMany("Divisions")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Department");
                });

            modelBuilder.Entity("GloryLikeBackend.Models.CompanyStructurePosition", b =>
                {
                    b.HasOne("GloryLikeBackend.Models.CompanyStructureDivision", "Division")
                        .WithMany("Positions")
                        .HasForeignKey("DivisionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Division");
                });

            modelBuilder.Entity("GloryLikeBackend.Models.CompanyHiringPlan", b =>
                {
                    b.HasOne("GloryLikeBackend.Models.User", "CompanyOwnerUser")
                        .WithMany()
                        .HasForeignKey("CompanyOwnerUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GloryLikeBackend.Models.User", "CreatedByUser")
                        .WithMany()
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GloryLikeBackend.Models.SkillAndJob.JobFamily", "JobFamily")
                        .WithMany()
                        .HasForeignKey("JobFamilyId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("GloryLikeBackend.Models.SkillAndJob.Position", "Position")
                        .WithMany()
                        .HasForeignKey("PositionId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("GloryLikeBackend.Models.SkillAndJob.Seniority", "Seniority")
                        .WithMany()
                        .HasForeignKey("SeniorityId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CompanyOwnerUser");
                    b.Navigation("CreatedByUser");
                    b.Navigation("JobFamily");
                    b.Navigation("Position");
                    b.Navigation("Seniority");
                });

            modelBuilder.Entity("GloryLikeBackend.Models.CompanyProfile", b =>
                {
                    b.HasOne("GloryLikeBackend.Models.User", "OwnerUser")
                        .WithMany()
                        .HasForeignKey("OwnerUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GloryLikeBackend.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UpdatedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("OwnerUser");
                });

            modelBuilder.Entity("GloryLikeBackend.Models.PendingEmailRegistration", b =>
                {
                    b.HasOne("GloryLikeBackend.Models.CompanyTeamInvitation", null)
                        .WithMany()
                        .HasForeignKey("TeamInvitationId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("GloryLikeBackend.Models.SkillAndJob.Position", b =>
                {
                    b.HasOne("GloryLikeBackend.Models.SkillAndJob.JobFamily", "JobFamily")
                        .WithMany("Positions")
                        .HasForeignKey("JobFamilyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("JobFamily");
                });

            modelBuilder.Entity("GloryLikeBackend.Models.SkillAndJob.PositionSeniority", b =>
                {
                    b.HasOne("GloryLikeBackend.Models.SkillAndJob.Position", "Position")
                        .WithMany("SeniorityLinks")
                        .HasForeignKey("PositionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GloryLikeBackend.Models.SkillAndJob.Seniority", "Seniority")
                        .WithMany("PositionLinks")
                        .HasForeignKey("SeniorityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Position");

                    b.Navigation("Seniority");
                });

            modelBuilder.Entity("GloryLikeBackend.Models.SkillAndJob.Skill", b =>
                {
                    b.HasOne("GloryLikeBackend.Models.SkillAndJob.Position", "Position")
                        .WithMany("Skills")
                        .HasForeignKey("PositionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Position");
                });

            modelBuilder.Entity("GloryLikeBackend.Models.Vacancies.Vacancy", b =>
                {
                    b.HasOne("GloryLikeBackend.Models.CompanyLocation", "CompanyLocation")
                        .WithMany()
                        .HasForeignKey("CompanyLocationId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("GloryLikeBackend.Models.CompanyHiringPlan", "HiringPlan")
                        .WithMany("Vacancies")
                        .HasForeignKey("HiringPlanId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("GloryLikeBackend.Models.User", null)
                        .WithMany()
                        .HasForeignKey("CompanyOwnerUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GloryLikeBackend.Models.User", null)
                        .WithMany()
                        .HasForeignKey("EmployerUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GloryLikeBackend.Models.SkillAndJob.JobFamily", null)
                        .WithMany()
                        .HasForeignKey("JobFamilyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GloryLikeBackend.Models.SkillAndJob.Position", null)
                        .WithMany()
                        .HasForeignKey("PositionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GloryLikeBackend.Models.SkillAndJob.Seniority", null)
                        .WithMany()
                        .HasForeignKey("SeniorityId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CompanyLocation");

                    b.Navigation("HiringPlan");
                });

            modelBuilder.Entity("GloryLikeBackend.Models.Vacancies.VacancyApplicationRequirement", b =>
                {
                    b.HasOne("GloryLikeBackend.Models.Vacancies.Vacancy", "Vacancy")
                        .WithMany("ApplicationRequirements")
                        .HasForeignKey("VacancyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Vacancy");
                });

            modelBuilder.Entity("GloryLikeBackend.Models.Vacancies.VacancyScreeningAnswer", b =>
                {
                    b.HasOne("GloryLikeBackend.Models.Vacancies.VacancyApplication", "VacancyApplication")
                        .WithMany("ScreeningAnswers")
                        .HasForeignKey("VacancyApplicationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("VacancyApplication");
                });

            modelBuilder.Entity("GloryLikeBackend.Models.Vacancies.VacancyApplication", b =>
                {
                    b.HasOne("GloryLikeBackend.Models.User", null)
                        .WithMany()
                        .HasForeignKey("CandidateUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GloryLikeBackend.Models.Vacancies.Vacancy", "Vacancy")
                        .WithMany("Applications")
                        .HasForeignKey("VacancyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Vacancy");
                });

            modelBuilder.Entity("GloryLikeBackend.Models.Vacancies.VacancyBenefit", b =>
                {
                    b.HasOne("GloryLikeBackend.Models.Vacancies.Vacancy", "Vacancy")
                        .WithMany("Benefits")
                        .HasForeignKey("VacancyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Vacancy");
                });

            modelBuilder.Entity("GloryLikeBackend.Models.Vacancies.VacancyFunnelStage", b =>
                {
                    b.HasOne("GloryLikeBackend.Models.Vacancies.Vacancy", "Vacancy")
                        .WithMany("FunnelStages")
                        .HasForeignKey("VacancyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Vacancy");
                });

            modelBuilder.Entity("GloryLikeBackend.Models.Vacancies.VacancyPublicationChannel", b =>
                {
                    b.HasOne("GloryLikeBackend.Models.Vacancies.Vacancy", "Vacancy")
                        .WithMany("PublicationChannels")
                        .HasForeignKey("VacancyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Vacancy");
                });

            modelBuilder.Entity("GloryLikeBackend.Models.Vacancies.VacancyScreeningQuestion", b =>
                {
                    b.HasOne("GloryLikeBackend.Models.Vacancies.Vacancy", "Vacancy")
                        .WithMany("ScreeningQuestions")
                        .HasForeignKey("VacancyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Vacancy");
                });

            modelBuilder.Entity("GloryLikeBackend.Models.Vacancies.VacancyScreeningChoice", b =>
                {
                    b.HasOne("GloryLikeBackend.Models.Vacancies.VacancyScreeningQuestion", "ScreeningQuestion")
                        .WithMany("Choices")
                        .HasForeignKey("ScreeningQuestionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ScreeningQuestion");
                });

            modelBuilder.Entity("GloryLikeBackend.Models.Vacancies.VacancySkillRequirement", b =>
                {
                    b.HasOne("GloryLikeBackend.Models.SkillAndJob.Skill", null)
                        .WithMany()
                        .HasForeignKey("SkillId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GloryLikeBackend.Models.Vacancies.Vacancy", "Vacancy")
                        .WithMany("SkillRequirements")
                        .HasForeignKey("VacancyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Vacancy");
                });

            modelBuilder.Entity("GloryLikeBackend.Models.SkillAndJob.JobFamily", b =>
                {
                    b.Navigation("Positions");
                });

            modelBuilder.Entity("GloryLikeBackend.Models.CompanyHiringPlan", b =>
                {
                    b.Navigation("Vacancies");
                });

            modelBuilder.Entity("GloryLikeBackend.Models.CompanyProfile", b =>
                {
                    b.Navigation("Locations");
                });

            modelBuilder.Entity("GloryLikeBackend.Models.CompanyStructureDepartment", b =>
                {
                    b.Navigation("Divisions");
                });

            modelBuilder.Entity("GloryLikeBackend.Models.CompanyStructureDivision", b =>
                {
                    b.Navigation("Positions");
                });

            modelBuilder.Entity("GloryLikeBackend.Models.SkillAndJob.Position", b =>
                {
                    b.Navigation("SeniorityLinks");

                    b.Navigation("Skills");
                });

            modelBuilder.Entity("GloryLikeBackend.Models.SkillAndJob.Seniority", b =>
                {
                    b.Navigation("PositionLinks");
                });

            modelBuilder.Entity("GloryLikeBackend.Models.Vacancies.VacancyApplication", b =>
                {
                    b.Navigation("ScreeningAnswers");
                });

            modelBuilder.Entity("GloryLikeBackend.Models.Vacancies.VacancyScreeningQuestion", b =>
                {
                    b.Navigation("Choices");
                });

            modelBuilder.Entity("GloryLikeBackend.Models.Vacancies.Vacancy", b =>
                {
                    b.Navigation("ApplicationRequirements");

                    b.Navigation("Applications");

                    b.Navigation("Benefits");

                    b.Navigation("FunnelStages");

                    b.Navigation("PublicationChannels");

                    b.Navigation("ScreeningQuestions");

                    b.Navigation("SkillRequirements");
                });
#pragma warning restore 612, 618
        }
    }
}
